#+SETUPFILE: ./blog-styles.org
#+TITLE: Finite Elements From Scratch (in Python)
#+SUBTITLE: and how to pick the right one for your simulation 
#+HTML: <p class="date"><i>last update: Jan 30, 2025</i></p>

#+BEGIN_EXPORT html
<div id="three-js-container"></div>
#+END_EXPORT
*Interactive* 3D visualization of a *reference tetrahedron* for a finite element mesh. _*Click and drag*_ to move around the mesh. 

#+BEGIN_EXPORT html
<script type="module" src="/assets/js/reference-tetrahedron.js"></script>
#+END_EXPORT

* Article Motivation 
#+BEGIN_QUOTE
- What is a finite element?
- How does it relate to a mesh?
- Which is the right element for my simulation?
- Code it in python.
#+END_QUOTE

* What is a finite element?
/Note: were talking about specific elements that are used in finite element analysis (FEA), not the finite element method (FEM) as a whole./

A finite element is a mathematical tool that serves as *building block for a numerical simulation* that uses the finite element method for its spatial discretization.

The rigous mathematical definition is usually taken from /The Mathematical Theory of Finite Element Methods/ by Brenner and Scott [cite:@brenner2008mathematical]. Their definition expands on the classic 1978 definition from P. Ciarlet [cite:@ciarlet1978finite].

#+BEGIN_emphasis
A finite element is a set that contains the following three objects:
1. A volume, $\mathcal{K}$,  with a piecewise smooth boundary.
2. A space of basis functions, $\mathcal{P}$.
3. A set of nodal points, $\mathcal{N} = {N_1, N_2, ..., N_k}$.
#+END_emphasis

All three of these are described by *sets*, hence the curly letters. Honestly, the fact that they are sets doesn't really concern me, because my goal is to code them up, not study their mathematical properties.

* References
#+print_bibliography:
