#+SETUPFILE: ./blog-styles.org
#+TITLE: What is a computational mesh?
#+SUBTITLE: The computational mesh in finite element analysis
#+BEGIN_EXPORT html
<div id="three-js-container"></div>
#+END_EXPORT

*Interactive* 3D mesh of the surface of a human brain. _*Click and drag*_ to move around the mesh. 

#+BEGIN_EXPORT html
<script type="module" src="/assets/js/simple-mesh.js"></script>
#+END_EXPORT

* Article Motivation 
#+BEGIN_QUOTE
- What is a computational mesh?
- How do we make a mathematical representation of a 3D bodies?
- What are the types of computational meshes?
- Why triangles?
#+END_QUOTE

* What is a computational mesh?
A computational mesh is a tool mathematicians use to represent real objects in mathematical simulations.

The idea is to take our real world domain, and break it up into small pieces (called *cells*), and solve our equations on each of these cells. This allows us to simplify our problem so we can quickly solve it in each cell. As the size of these cells goes to zero, the error for our simulation will also tend to zero.

For our purposes we want to understand *3D tetrahedral unstructured meshes*. These types of meshes allow for cutting edge numerical simulations on complex 3D geometry.

Tetrahedral means each cell in our mesh is a tetrahedron (a figure enclosed by four triangles)

Unstructured means each cell can be a different size and shape.

* What constitutes an object?
Consider for a moment that you want to solve a partial differential equation (for example [[./the-acoustic-wave-equations.html][the acoustic wave equations]]), and you want to do it over some object (the brain for example). How do you mathematically represent that object?

Our goal is to run a numerical simulation in 3D. To achieve that goal, we need to be able to describe the shape of a 3D object mathematically.

For a perfect sphere that is simple. 
